---
- name: Apt-Packages | Install core apt-packages
  hosts: localhost
  become: true

  pre_tasks:

    - name: Apt-Packages | Check if running on Linux Mint
      ansible.builtin.shell: cat /etc/os-release | grep 'Linux Mint'
      register: is_linux_mint
      changed_when: false
      failed_when: false

    - name: Apt-Packages | Backup nosnap.pref if on Linux Mint
      ansible.builtin.command: mv /etc/apt/preferences.d/nosnap.pref /etc/apt/preferences.d/nosnap.pref.bak
      when: is_linux_mint.stdout != ""

    - name: Apt-Packages | Update APT cache
      include_role:
        name: update_apt

  tasks:
    - name: Apt-Packages | All the apt-packages I like
      block:
        - name: Install apt packages
          apt:
            name: 
              - snapd
              - git
              - fonts-powerline
              - tmux
              - ripgrep
              - pavucontrol
              - mpv
              - xclip
              - gimp
              - htop
              - eza
              - jq
              - tldr
              - shutter
              - blueman
              - unzip
              - tar
              - make # Should always be present on linux but you never know
            state: present
            update_cache: yes
      rescue:
        - name: Restore nosnap.pref on failure
          ansible.builtin.command: mv /etc/apt/preferences.d/nosnap.pref.bak /etc/apt/preferences.d/nosnap.pref
          when: is_linux_mint.stdout != ""
        - name: Set a flag indicating rescue was triggered
          ansible.builtin.set_fact:
            rescue_triggered: true

  post_tasks:
    - name: Check if nosnap.pref.bak exists
      ansible.builtin.stat:
        path: /etc/apt/preferences.d/nosnap.pref.bak
      register: nosnap_pref_backup

    - name: Restore nosnap.pref if on Linux Mint and not already restored
      ansible.builtin.command: mv /etc/apt/preferences.d/nosnap.pref.bak /etc/apt/preferences.d/nosnap.pref
      when: 
        - is_linux_mint.stdout != ""
        - nosnap_pref_backup.stat.exists