---
- name: Apt-Packages | Install core apt-packages
  hosts: localhost

  pre_tasks:
    - name: Update APT cache
      include_role:
        name: update_apt

  tasks:
    - name: Apt-Packages | All the apt-packages I like
      become: true
      apt:
        name: 
          - git
          - fonts-powerline
          - tmux
          - ripgrep
          - pavucontrol
          - mpv
          - xclip
          - gimp
          - htop
          - exa
          - jq
          - tldr
          - shutter
          - blueman
          - unzip
          - tar
          - make # Should always be present on linux but you never know
        state: present
        update_cache: yes
