---
- name: Apt-Packages | Install core apt-packages
  hosts: localhost
  connection: local
  become: true

  pre_tasks:

    - name: Apt-Packages | Check if running on Linux Mint
      ansible.builtin.shell: cat /etc/os-release | grep 'Linux Mint'
      register: is_linux_mint
      changed_when: false
      failed_when: false

    - name: Apt-Packages | Backup nosnap.pref if on Linux Mint
      ansible.builtin.command: mv /etc/apt/preferences.d/nosnap.pref /etc/apt/preferences.d/nosnap.pref.bak
      when: is_linux_mint.stdout != ""

    - name: Apt-Packages | Update APT cache
      ansible.builtin.include_role:
        name: update_apt

  tasks:
    - name: Apt-Packages | All the apt-packages I like
      block:
        - name: Install apt packages
          ansible.builtin.apt:
            name:
              - snapd
              - git
              - fonts-powerline
              - tmux
              - ripgrep
              - pavucontrol
              - mpv
              - xclip # clipboard library
              - gimp
              - htop
              - eza #TODO: find the error here...why can't I apt-get install eza on ubuntu 24.04 -> previously exa, see my tree script
              - net-tools # netstat and the like
              - jq
              - xdotool # workspace manipulation
              - tldr
              - openssh-server
              - shutter # advanced screenshots
              - blueman # bluetooth
              - unzip
              - tar
              - make # Should always be present on linux but you never know
              - kdeconnect
              - maim # screenshots in i3
              - xfce4-appfinder
              - apache2-utils # ab apache-benchmark
              - vim
            state: present
            update_cache: yes
      rescue:
        - name: Restore nosnap.pref on failure
          ansible.builtin.command: mv /etc/apt/preferences.d/nosnap.pref.bak /etc/apt/preferences.d/nosnap.pref
          when: is_linux_mint.stdout != ""
        - name: Set a flag indicating rescue was triggered
          ansible.builtin.set_fact:
            rescue_triggered: true

  post_tasks:
    - name: Check if nosnap.pref.bak exists
      ansible.builtin.stat:
        path: /etc/apt/preferences.d/nosnap.pref.bak
      register: nosnap_pref_backup

    - name: Restore nosnap.pref if on Linux Mint and not already restored
      ansible.builtin.command: mv /etc/apt/preferences.d/nosnap.pref.bak /etc/apt/preferences.d/nosnap.pref
      when:
        - is_linux_mint.stdout != ""
        - nosnap_pref_backup.stat.exists
