---
- name: k9s | Install k9s
  hosts: localhost
  connection: local
  become: true

  pre_tasks:
    - name: k9s | Update APT cache
      ansible.builtin.include_role:
        name: update_apt

  tasks:
  - name: Include main vars
    ansible.builtin.include_vars:
      file: ../vars.yml

  - name: k9s | wget k9s .deb (linux amd64)
    ansible.builtin.get_url:
      url: https://github.com/derailed/k9s/releases/latest/download/k9s_linux_amd64.deb
      dest: /tmp/k9s_linux_amd64.deb

  - name: k9s | install k9s package
    ansible.builtin.apt:
      deb: /tmp/k9s_linux_amd64.deb
      state: present

  - name: k9s | remove k9s package after installation
    ansible.builtin.file:
      path: /tmp/k9s_linux_amd64.deb
      state: absent
