---
- name: Obsidian | Update and install Obsidian
  hosts: localhost
  become: true

  tasks:
    - name: Obsidian | Remove existing Obsidian installation
      apt:
        name: obsidian
        state: absent

    - name: Obsidian | Find Obsidian binary location
      command: whereis obsidian
      register: whereis_obsidian
      changed_when: false

    - name: Obsidian | Remove Obsidian binary if it exists
      file:
        path: "{{ item }}"
        state: absent
      with_items: "{{ whereis_obsidian.stdout.split()[1:] }}"
      when: whereis_obsidian.stdout != 'obsidian:'

    - name: Obsidian | Download Obsidian deb package
      get_url:
        url: https://github.com/obsidianmd/obsidian-releases/releases/download/v1.6.7/obsidian_1.6.7_amd64.deb
        dest: /tmp/obsidian_1.6.7_amd64.deb
        mode: '0644'

    - name: Obsidian | Install Obsidian deb package
      apt:
        deb: /tmp/obsidian_1.6.7_amd64.deb
