---
- name: vim | Install vim
  hosts: localhost
  connection: local
  become: true

  pre_tasks:
    - name: vim | Update APT cache
      ansible.builtin.include_role:
        name: update_apt

  tasks:
    - name: vim | install vim
      ansible.builtin.apt:
        name:
          - vim
        state: present
        update_cache: yes

    - name: vim | Set vim.basic as default editor
      ansible.builtin.command: update-alternatives --set editor /usr/bin/vim.basic
