---
- name: Ctop | Install docker-ctop
  hosts: localhost
  become: true

  tasks:
    - name: Download ctop binary
      get_url:
        url: https://github.com/bcicen/ctop/releases/download/v0.7.7/ctop-0.7.7-linux-amd64
        dest: /usr/local/bin/ctop
        mode: '0755'
