---
- name: FZF | Install Fuzzyfinder
  hosts: localhost

  vars_files:
    - ../vars.yml

  tasks:
    - name: FZF | Install special packages (fzf) # Apt version of fzf is way to old
      become: false
      become_user: "{{ current_user}}"
      ansible.builtin.git:
        repo: 'https://github.com/junegunn/fzf.git'
        dest: "{{ lookup('env', 'HOME') }}/.fzf"
        depth: 1