- name: Tmux | Install tmux
- hosts: localhost

  vars_files:
    - ../vars.yml

  pre_tasks:
    - name: Update APT cache
      include_role:
        name: update_apt

  tasks:
    - name: Tmux | Installing tmux
      become: true
      apt:
        name: tmux
        state: present
        update_cache: yes