---
- name: Install core apt-packages
  hosts: localhost

  pre_tasks:
    - name: Include pre-tasks to update apt
      import_tasks: update_apt.yml

  tasks:
    - name: I3 | Download the i3wm signing key (tarball) from sur5r.net
      ansible.builtin.get_url:
        url: https://debian.sur5r.net/i3/pool/main/s/sur5r-keyring/sur5r-keyring_2024.03.04_all.deb 
        dest: /tmp/keyring.deb 
        checksum: sha256:f9bb4340b5ce0ded29b7e014ee9ce788006e9bbfe31e96c09b2118ab91fca734

    - name: I3 |Return motd to registered var
      become: true
      ansible.builtin.command: apt install /tmp/keyring.deb

    - name: I3 |Return motd to registered var
      become: true
      ansible.builtin.command: echo "deb http://debian.sur5r.net/i3/ $(grep '^DISTRIB_CODENAME=' /etc/lsb-release | cut -f2 -d=) universe" | tee /etc/apt/sources.list.d/sur5r-i3.list

    - name: I3 |Install i3
      become: true
      ansible.builtin.apt:
        name: i3
        update_cache: yes