---
- name: Install I3
  hosts: localhost

  pre_tasks:
    - name: Update APT cache
      include_role:
        name: update_apt

  tasks:
    - name: I3 | Download the i3wm signing key (tarball) from sur5r.net
      ansible.builtin.get_url:
        url: https://debian.sur5r.net/i3/pool/main/s/sur5r-keyring/sur5r-keyring_2025.12.14_all.deb 
        dest: /tmp/keyring.deb 
        checksum: sha256:2c816fbd12ea4d84811818aed0ce3a5da589be1afa30833eb32abc1e4fe6349e

    - name: I3 | Return motd to registered var
      become: true
      ansible.builtin.command: apt install /tmp/keyring.deb

    - name: I3 | Return motd to registered var
      become: true
      ansible.builtin.command: echo "deb http://debian.sur5r.net/i3/ $(grep '^DISTRIB_CODENAME=' /etc/lsb-release | cut -f2 -d=) universe" | tee /etc/apt/sources.list.d/sur5r-i3.list

    - name: I3 | Install i3
      become: true
      ansible.builtin.apt:
        name: i3
        update_cache: yes
