---
- name: Ufw-Firewall | Install and enable UFW firewall
  hosts: localhost
  become: true

  pre_tasks:
    - name: Update APT cache
      include_role:
        name: update_apt

  tasks:
    - name: Ufw-Firewall |Install UFW
      ansible.builtin.apt:
        name: ufw
        state: present

    - name: Ufw-Firewall |Enable UFW
      ansible.builtin.shell: |
        sudo ufw enable

    - name: Ufw-Firewall |Ensure UFW is enabled
      ansible.builtin.shell: |
        sudo ufw status | grep -qw 'Status: active'
      register: ufw_status_check
      changed_when: false
      failed_when: ufw_status_check.rc != 0
