Host gitlab.com-christoph
  HostName gitlab.com
  User git
  IdentityFile ~/.ssh/id_ed25519
  IdentitiesOnly yes

Host github.com
  HostName github.com
  User git
  IdentityFile ~/.ssh/id_ed25519_github_vincentvancode101

Host github.com-second-brain
    HostName github.com
    User git
    IdentityFile ~/.ssh/id_second-brain_deploy
    IdentitiesOnly yes

Host lab-1
  HostName 192.168.1.103
  User christoph
  IdentityFile ~/.ssh/id_ed25519
  IdentitiesOnly yes

Host main
  HostName 192.168.1.104
  User christoph
  IdentityFile ~/.ssh/id_ed25519
  IdentitiesOnly yes