#!/usr/bin/env bash
sudo apt install git
git clone https://github.com/VincentVanCode101/ansible $1
sudo apt update
sudo apt install software-properties-common
sudo add-apt-repository --yes --update ppa:ansible/ansible
sudo apt install -y ansible
