---
- name: Brew-Packages | Install core Homebrew formulae & casks
  hosts: localhost
  connection: local
  gather_facts: true
  vars:
    brew_formulae:
      - git
      - tmux
      - neovim
      - htop
      - wget
      - jq
      - gimp
      - stow
      - fswatch
      - coreutils
      - zsh-autosuggestions
    brew_casks:
      - google-chrome
      - brave-browser
      - iterm2
      - spotify
      - discord
      - libreoffice
      - obs
  tasks:

    - name: Ensure we're on macOS
      ansible.builtin.assert:
        that:
          - ansible_facts['os_family'] == 'Darwin'
        fail_msg: "This playbook only works on macOS (Darwin)."

    - name: Brew-Packages | Ensure Homebrew is installed
      community.general.homebrew:
        state: present

    - name: Brew-Packages | Install Homebrew formulae
      community.general.homebrew:
        name: "{{ brew_formulae }}"
        state: present

    - name: Brew-Packages | Install Homebrew casks
      community.general.homebrew_cask:
        name: "{{ brew_casks }}"
        state: present
