---
- name: WhatsApp | macOS Installation via DMG
  hosts: localhost
  connection: local
  become: true

  pre_tasks:
    - name: Determine if this is macOS
      ansible.builtin.set_fact:
        is_darwin: "{{ ansible_facts['system'] == 'Darwin' }}"

  tasks:
    - block:
        - name: WhatsApp | Create temporary directory for download
          ansible.builtin.file:
            path: /tmp/whatsapp_install
            state: directory
            mode: '0755'

        - name: WhatsApp | Download WhatsApp DMG (macOS)
          ansible.builtin.get_url:
            url: "https://web.whatsapp.com/desktop/mac_native/release/?configuration=Release"
            dest: /tmp/whatsapp_install/WhatsApp.dmg
            mode: '0644'

        - name: WhatsApp | Attach WhatsApp DMG (macOS)
          ansible.builtin.command:
            cmd: hdiutil attach /tmp/whatsapp_install/WhatsApp.dmg -nobrowse
          register: attach_result

        - name: WhatsApp | Find mounted WhatsApp.app directory (macOS)
          ansible.builtin.find:
            paths: /Volumes
            patterns: "WhatsApp.app"
            recurse: yes
            file_type: directory
          register: whatsapp_app

        - name: WhatsApp | Fail if WhatsApp.app wasn’t found
          ansible.builtin.fail:
            msg: "Could not find WhatsApp.app under /Volumes after mounting the DMG."
          when: whatsapp_app.matched == 0

        - name: WhatsApp | Copy WhatsApp.app into /Applications
          ansible.builtin.command:
            cmd: cp -R "{{ whatsapp_app.files[0].path }}" /Applications/
          args:
            creates: /Applications/WhatsApp.app

        - name: WhatsApp | Ensure ownership of WhatsApp.app in /Applications
          ansible.builtin.file:
            path: /Applications/WhatsApp.app
            owner: "{{ lookup('env','USER') }}"
            group: staff
            recurse: yes

        - name: WhatsApp | Set mount_dir fact for detaching
          ansible.builtin.set_fact:
            mount_dir: "{{ whatsapp_app.files[0].path | dirname }}"

        - name: WhatsApp |Detach WhatsApp DMG
          ansible.builtin.command:
            cmd: hdiutil detach "{{ mount_dir }}" -quiet

        - name: WhatsApp | Remove temporary download directory
          ansible.builtin.file:
            path: /tmp/whatsapp_install
            state: absent
      when: is_darwin
