- hosts: localhost

  tasks:
  - name: Include main vars
    ansible.builtin.include_vars:
      file: vars.yml

  - name: Neovim | Remove old versions of neovim
    ansible.builtin.file:
       path: "{{ home }}/neovim"
       state: absent

  - name: Neovim | Clone neovim
    ansible.builtin.git:
       repo: https://github.com/neovim/neovim.git
       dest: "{{ home }}/neovim"
       depth: 1
       version: stable

  - name: Neovim | Install neovim deps
    become: true
    apt:
      name: "{{ packages }}"
      state: present
    vars:
      packages:
      - cmake
      - gettext
      - lua5.1
      - liblua5.1-0-dev

  - name: Neovim | Make Install Neovim
    become: true
    ansible.builtin.command: sudo make install
    args:
      chdir: "{{ home }}/neovim"
