- hosts: localhost

  vars_files:
    - vars.yml

  pre_tasks:
    - name: Include pre-tasks to update apt
      import_tasks: update_apt.yml

  tasks:
    - name: installing tmux
      become: true
      apt:
        name: tmux
        state: present
        update_cache: yes