---
- name: java | Install java
  hosts: localhost
  become: true

  pre_tasks:
    - name: java | Update APT cache
      include_role:
        name: update_apt

  tasks:
    - name: java | install default jdk
      apt:
        name: 
          - default-jdk
        state: present
        update_cache: yes