---
- name: discord | Install discord
  hosts: localhost
  connection: local
  become: true

  tasks:
    - name: discord | Install Discord from the Snap Store
      community.general.snap:
        name: discord
        state: present