---
- name: KeePassXC | Install KeePassXC
  hosts: localhost
  become: true

  pre_tasks:
    - name: Update APT cache
      include_role:
        name: update_apt

  tasks:
  - name: KeePassXC | Add KeePassXC PPA
    ansible.builtin.apt_repository:
      repo: ppa:phoerious/keepassxc
      state: present

  - name: KeePassXC | Install KeePassXC
    apt:
      name: ["keepassxc"]
      state: present