- name: Install Gimp
  hosts: localhost
  become: true

  pre_tasks:
    - name: Include pre-tasks to update apt
      import_tasks: update_apt.yml

  tasks:
  - name: KeePassXC | Add KeePassXC PPA
    ansible.builtin.apt_repository:
      repo: ppa:phoerious/keepassxc
      state: present

  - name: KeePassXC | Install KeePassXC
    apt:
      name: ["keepassxc"]
      state: present