---
- name: Okular | Install pdf-reader (okular)
  hosts: localhost
  become: true

  pre_tasks:
    - name: Update APT cache
      include_role:
        name: update_apt

  tasks:
    - name: Okular | Install pdf-reader (okular)
      become: true
      apt:
        name: ["okular"]
        state: present