current_user: "{{ lookup('ansible.builtin.env', 'USER') }}"
home: "{{ lookup('ansible.builtin.env', 'HOME') }}"
personal: "{{ home }}/personal"

ssh_keys:
  - id_rsa
  - id_ed25519
  - id_second-brain_deploy
  - id_ed25519_github_vincentvancode101
ssh_key_dir: "{{ lookup('env', 'HOME') }}/.ssh"
source_key_dir: "../../resources/.ssh"

oh_my_zsh_path: "/home/{{ current_user }}/.oh-my-zsh"
zshrc_path: "/home/{{ current_user }}/.zshrc"
zsh_profile_path: "/home/{{ current_user }}/.zsh_profile"
zsh_autosuggestions_dest: "{{ oh_my_zsh_path }}/custom/plugins/zsh-autosuggestions"
powerlevel10k_dest: "{{ oh_my_zsh_path }}/custom/themes/powerlevel10k"
zsh_dependencies: []

important_repo_git_urls:
  - git@github.com:VincentVanCode101/craft.git
  - git@github.com:VincentVanCode101/shellcheck.git
  - git@github.com:VincentVanCode101/docker-apps.git
  - git@github.com:VincentVanCode101/the-beter-git-init.git