---
- name: Dotfiles | Set up my dotfiles
  hosts: localhost
  vars_files:
    - ../vars.yml

  pre_tasks:
    - name: Dotfiles | Update APT cache
      include_role:
        name: update_apt

  tasks:
    - name: Dotfiles |Installing stow
      become: true
      apt: 
        name: stow

    - name: Dotfiles | Source SSH agent environment
      shell: |
        source /tmp/agent_env
        ssh-add -l  # List loaded keys to verify
      args:
        executable: /bin/bash
      register: ssh_agent_check
      ignore_errors: yes

    - name: Dotfiles | Check if SSH agent is running
      fail:
        msg: "SSH agent is not running, or SSH keys are not loaded correctly."
      when: ssh_agent_check.rc != 0


    - name: Dotfiles | Cloning dotfiles
      become: false
      become_user: "{{ current_user }}"
      ansible.builtin.git:
        repo: 'git@gitlab.com:christoph.tech101/dotfiles.git'
        dest: "{{ lookup('env', 'HOME') }}/dotfiles"
        recursive: yes
        update: yes
        accept_hostkey: yes
        version: main

    - name: Dotfiles | Clean environment by removing existing unstowing & removing dotfiles
      shell: cd $HOME/dotfiles && ./ubuntu --clean-env
      args:
        executable: /bin/zsh

    - name: Dotfiles | Stow dotfiles
      shell: cd $HOME/dotfiles && ./ubuntu --install
      args:
        executable: /bin/zsh
