---
- name: Dotfiles | Set up my dotfiles
  hosts: localhost
  vars_files:
    - ../vars.yml

  pre_tasks:
    - name: Update APT cache
      include_role:
        name: update_apt

  tasks:
    - name: Dotfiles | Installing stow
      become: true
      apt: 
        name: stow

    - name: Dotfiles | Start ssh-agent
      ansible.builtin.shell: eval $(ssh-agent)
      register: ssh_agent_output

    - name: Debug SSH_AUTH_SOCK environment variable
      debug:
        msg: "SSH_AUTH_SOCK is set to {{ ssh_agent_output.stdout }}"

    - name: Dotfiles | Add SSH keys with passphrases to ssh-agent
      ansible.builtin.expect:
        command: ssh-add "{{ ssh_key_dir }}/{{ item }}"
        responses:
          "Enter passphrase for {{ ssh_key_dir }}/{{ item }}:": "{{ lookup('password_prompt', 'SSH Key Passphrase for ' ~ item) }}"
      with_items: "{{ ssh_keys }}"
      # environment:
      #   SSH_AUTH_SOCK: "{{ ssh_agent_output.stdout_lines[-1].split('=')[1].split(';')[0] }}"

    - name: Dotfiles | Cloning dotfiles
      become: false
      become_user: "{{ current_user }}"
      ansible.builtin.git:
        repo: 'git@gitlab.com:christoph.tech101/dotfiles.git'
        dest: "{{ lookup('env', 'HOME') }}/dotfiles"
        recursive: yes
        update: yes
        accept_hostkey: yes
        version: main
      # environment:
        # SSH_AUTH_SOCK: "{{ ssh_agent_output.stdout_lines[-1].split('=')[1].split(';')[0] }}"

    - name: Dotfiles | Clean environment by removing existing dotfiles
      shell: cd $HOME/dotfiles && ./clean-env
      args:
        executable: /bin/zsh

    - name: Dotfiles | Stow dotfiles
      shell: cd $HOME/dotfiles && ./ubuntu
      args:
        executable: /bin/zsh
